# Generated by Django 3.0.3 on 2020-02-20 12:21

from django.conf import settings
from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='slug')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='address')),
                ('location',
                 location_field.models.plain.PlainLocationField(default='-22.2876834,-49.1607606', max_length=63)),
                (
                    'logo',
                    models.ImageField(blank=True, null=True, upload_to='map/restaurant/logo', verbose_name='logo')),
                ('phone_number', models.CharField(blank=True, default='', max_length=25, verbose_name='phone number')),
                (
                    'instagram_url',
                    models.URLField(blank=True, default='', max_length=150, verbose_name='instagram URL')),
                ('facebook_url', models.URLField(blank=True, default='', max_length=150, verbose_name='facebook URL')),
                ('website', models.URLField(blank=True, default='', max_length=150, verbose_name='website')),
                ('twitter_url', models.URLField(blank=True, default='', max_length=150, verbose_name='twitter URL')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('staff',
                 models.ManyToManyField(related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='staff')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
            },
        ),
    ]
