# Generated by Django 3.0.3 on 2020-02-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurant', '0003_allergen_category_dish_lifestyle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergen',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='lifestyle',
            name='dish',
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen',
            field=models.ManyToManyField(related_name='dishes', to='restaurant.Allergen', verbose_name='allergen'),
        ),
        migrations.AddField(
            model_name='dish',
            name='lifestyle',
            field=models.ManyToManyField(related_name='dishes', to='restaurant.Lifestyle', verbose_name='lifestyle'),
        ),
    ]
