# Generated by Django 3.0.3 on 2020-02-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurant', '0004_auto_20200220_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='filters_active',
            field=models.BooleanField(default=False, verbose_name='filters active'),
        ),
    ]
